name: uniffi_xforge
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  libforge_dart:
    path: ../../../adapters/dart
  path: ^1.9.0
  ffi: ^2.1.4
  hooks: ^1.0.0
  native_toolchain_rust: ^1.0.0
